CC=gcc
CFLAGS=-o 

all: src/main.c src/linked_list.c src/functions.c src/file_io.c include/linked_list.h include/functions.h include/file_io.h
	$(CC) -o client src/main.c src/linked_list.c src/functions.c src/file_io.c
clean:
	rm -f main

